#spring:
#  redis:
#    host: 82.157.251.233
#    port: 6379
#    password: xzkj1225
#    jedis:
#      pool:
#        max-active: 20
#        max-idle: 8
#        max-wait: 20000
#        min-idle: 0
#  rabbitmq:
#    host: 82.157.251.233
#    port: 5672
#    username: admin
#    password: xzkj1225
#    publisher-confirm-type: correlated
#    publisher-returns: true
logging:
  level:
    root: info
