// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.xzkj.ossService.entity;

public final class TStudent {
  private TStudent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StudentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Student)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * message Person中新增字段
     * </pre>
     *
     * <code>optional .google.protobuf.Duration duration = 6;</code>
     * @return Whether the duration field is set.
     */
    boolean hasDuration();
    /**
     * <pre>
     * message Person中新增字段
     * </pre>
     *
     * <code>optional .google.protobuf.Duration duration = 6;</code>
     * @return The duration.
     */
    com.google.protobuf.Duration getDuration();
    /**
     * <pre>
     * message Person中新增字段
     * </pre>
     *
     * <code>optional .google.protobuf.Duration duration = 6;</code>
     */
    com.google.protobuf.DurationOrBuilder getDurationOrBuilder();

    /**
     * <code>optional int32 number = 1;</code>
     * @return Whether the number field is set.
     */
    boolean hasNumber();
    /**
     * <code>optional int32 number = 1;</code>
     * @return The number.
     */
    int getNumber();

    /**
     * <code>optional string name = 2;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <code>optional string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 sex = 3;</code>
     * @return Whether the sex field is set.
     */
    boolean hasSex();
    /**
     * <code>optional int32 sex = 3;</code>
     * @return The sex.
     */
    int getSex();

    /**
     * <code>optional string hobby = 4;</code>
     * @return Whether the hobby field is set.
     */
    boolean hasHobby();
    /**
     * <code>optional string hobby = 4;</code>
     * @return The hobby.
     */
    java.lang.String getHobby();
    /**
     * <code>optional string hobby = 4;</code>
     * @return The bytes for hobby.
     */
    com.google.protobuf.ByteString
        getHobbyBytes();

    /**
     * <code>optional string skill = 5;</code>
     * @return Whether the skill field is set.
     */
    boolean hasSkill();
    /**
     * <code>optional string skill = 5;</code>
     * @return The skill.
     */
    java.lang.String getSkill();
    /**
     * <code>optional string skill = 5;</code>
     * @return The bytes for skill.
     */
    com.google.protobuf.ByteString
        getSkillBytes();
  }
  /**
   * <pre>
   *java_outer_classname与message 名称不能相同
   * </pre>
   *
   * Protobuf type {@code Student}
   */
  public static final class Student extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Student)
      StudentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Student.newBuilder() to construct.
    private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Student() {
      name_ = "";
      hobby_ = "";
      skill_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Student();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xzkj.ossService.entity.TStudent.internal_static_Student_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xzkj.ossService.entity.TStudent.internal_static_Student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xzkj.ossService.entity.TStudent.Student.class, com.xzkj.ossService.entity.TStudent.Student.Builder.class);
    }

    private int bitField0_;
    public static final int DURATION_FIELD_NUMBER = 6;
    private com.google.protobuf.Duration duration_;
    /**
     * <pre>
     * message Person中新增字段
     * </pre>
     *
     * <code>optional .google.protobuf.Duration duration = 6;</code>
     * @return Whether the duration field is set.
     */
    @java.lang.Override
    public boolean hasDuration() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * message Person中新增字段
     * </pre>
     *
     * <code>optional .google.protobuf.Duration duration = 6;</code>
     * @return The duration.
     */
    @java.lang.Override
    public com.google.protobuf.Duration getDuration() {
      return duration_ == null ? com.google.protobuf.Duration.getDefaultInstance() : duration_;
    }
    /**
     * <pre>
     * message Person中新增字段
     * </pre>
     *
     * <code>optional .google.protobuf.Duration duration = 6;</code>
     */
    @java.lang.Override
    public com.google.protobuf.DurationOrBuilder getDurationOrBuilder() {
      return duration_ == null ? com.google.protobuf.Duration.getDefaultInstance() : duration_;
    }

    public static final int NUMBER_FIELD_NUMBER = 1;
    private int number_;
    /**
     * <code>optional int32 number = 1;</code>
     * @return Whether the number field is set.
     */
    @java.lang.Override
    public boolean hasNumber() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 number = 1;</code>
     * @return The number.
     */
    @java.lang.Override
    public int getNumber() {
      return number_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEX_FIELD_NUMBER = 3;
    private int sex_;
    /**
     * <code>optional int32 sex = 3;</code>
     * @return Whether the sex field is set.
     */
    @java.lang.Override
    public boolean hasSex() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 sex = 3;</code>
     * @return The sex.
     */
    @java.lang.Override
    public int getSex() {
      return sex_;
    }

    public static final int HOBBY_FIELD_NUMBER = 4;
    private volatile java.lang.Object hobby_;
    /**
     * <code>optional string hobby = 4;</code>
     * @return Whether the hobby field is set.
     */
    @java.lang.Override
    public boolean hasHobby() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string hobby = 4;</code>
     * @return The hobby.
     */
    @java.lang.Override
    public java.lang.String getHobby() {
      java.lang.Object ref = hobby_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hobby_ = s;
        return s;
      }
    }
    /**
     * <code>optional string hobby = 4;</code>
     * @return The bytes for hobby.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHobbyBytes() {
      java.lang.Object ref = hobby_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hobby_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SKILL_FIELD_NUMBER = 5;
    private volatile java.lang.Object skill_;
    /**
     * <code>optional string skill = 5;</code>
     * @return Whether the skill field is set.
     */
    @java.lang.Override
    public boolean hasSkill() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string skill = 5;</code>
     * @return The skill.
     */
    @java.lang.Override
    public java.lang.String getSkill() {
      java.lang.Object ref = skill_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        skill_ = s;
        return s;
      }
    }
    /**
     * <code>optional string skill = 5;</code>
     * @return The bytes for skill.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSkillBytes() {
      java.lang.Object ref = skill_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        skill_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(1, number_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(3, sex_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, hobby_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, skill_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(6, getDuration());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, number_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, sex_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, hobby_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, skill_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getDuration());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xzkj.ossService.entity.TStudent.Student)) {
        return super.equals(obj);
      }
      com.xzkj.ossService.entity.TStudent.Student other = (com.xzkj.ossService.entity.TStudent.Student) obj;

      if (hasDuration() != other.hasDuration()) return false;
      if (hasDuration()) {
        if (!getDuration()
            .equals(other.getDuration())) return false;
      }
      if (hasNumber() != other.hasNumber()) return false;
      if (hasNumber()) {
        if (getNumber()
            != other.getNumber()) return false;
      }
      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasSex() != other.hasSex()) return false;
      if (hasSex()) {
        if (getSex()
            != other.getSex()) return false;
      }
      if (hasHobby() != other.hasHobby()) return false;
      if (hasHobby()) {
        if (!getHobby()
            .equals(other.getHobby())) return false;
      }
      if (hasSkill() != other.hasSkill()) return false;
      if (hasSkill()) {
        if (!getSkill()
            .equals(other.getSkill())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDuration()) {
        hash = (37 * hash) + DURATION_FIELD_NUMBER;
        hash = (53 * hash) + getDuration().hashCode();
      }
      if (hasNumber()) {
        hash = (37 * hash) + NUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getNumber();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasSex()) {
        hash = (37 * hash) + SEX_FIELD_NUMBER;
        hash = (53 * hash) + getSex();
      }
      if (hasHobby()) {
        hash = (37 * hash) + HOBBY_FIELD_NUMBER;
        hash = (53 * hash) + getHobby().hashCode();
      }
      if (hasSkill()) {
        hash = (37 * hash) + SKILL_FIELD_NUMBER;
        hash = (53 * hash) + getSkill().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xzkj.ossService.entity.TStudent.Student parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xzkj.ossService.entity.TStudent.Student parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xzkj.ossService.entity.TStudent.Student parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xzkj.ossService.entity.TStudent.Student parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xzkj.ossService.entity.TStudent.Student parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xzkj.ossService.entity.TStudent.Student parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xzkj.ossService.entity.TStudent.Student parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xzkj.ossService.entity.TStudent.Student parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xzkj.ossService.entity.TStudent.Student parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xzkj.ossService.entity.TStudent.Student parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xzkj.ossService.entity.TStudent.Student parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xzkj.ossService.entity.TStudent.Student parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xzkj.ossService.entity.TStudent.Student prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *java_outer_classname与message 名称不能相同
     * </pre>
     *
     * Protobuf type {@code Student}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Student)
        com.xzkj.ossService.entity.TStudent.StudentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xzkj.ossService.entity.TStudent.internal_static_Student_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xzkj.ossService.entity.TStudent.internal_static_Student_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xzkj.ossService.entity.TStudent.Student.class, com.xzkj.ossService.entity.TStudent.Student.Builder.class);
      }

      // Construct using com.xzkj.ossService.entity.TStudent.Student.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDurationFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (durationBuilder_ == null) {
          duration_ = null;
        } else {
          durationBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        number_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        sex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        hobby_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        skill_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xzkj.ossService.entity.TStudent.internal_static_Student_descriptor;
      }

      @java.lang.Override
      public com.xzkj.ossService.entity.TStudent.Student getDefaultInstanceForType() {
        return com.xzkj.ossService.entity.TStudent.Student.getDefaultInstance();
      }

      @java.lang.Override
      public com.xzkj.ossService.entity.TStudent.Student build() {
        com.xzkj.ossService.entity.TStudent.Student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xzkj.ossService.entity.TStudent.Student buildPartial() {
        com.xzkj.ossService.entity.TStudent.Student result = new com.xzkj.ossService.entity.TStudent.Student(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (durationBuilder_ == null) {
            result.duration_ = duration_;
          } else {
            result.duration_ = durationBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.number_ = number_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.sex_ = sex_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.hobby_ = hobby_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.skill_ = skill_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xzkj.ossService.entity.TStudent.Student) {
          return mergeFrom((com.xzkj.ossService.entity.TStudent.Student)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xzkj.ossService.entity.TStudent.Student other) {
        if (other == com.xzkj.ossService.entity.TStudent.Student.getDefaultInstance()) return this;
        if (other.hasDuration()) {
          mergeDuration(other.getDuration());
        }
        if (other.hasNumber()) {
          setNumber(other.getNumber());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000004;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasSex()) {
          setSex(other.getSex());
        }
        if (other.hasHobby()) {
          bitField0_ |= 0x00000010;
          hobby_ = other.hobby_;
          onChanged();
        }
        if (other.hasSkill()) {
          bitField0_ |= 0x00000020;
          skill_ = other.skill_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                number_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 18
              case 24: {
                sex_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 24
              case 34: {
                hobby_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 34
              case 42: {
                skill_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 42
              case 50: {
                input.readMessage(
                    getDurationFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Duration duration_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder> durationBuilder_;
      /**
       * <pre>
       * message Person中新增字段
       * </pre>
       *
       * <code>optional .google.protobuf.Duration duration = 6;</code>
       * @return Whether the duration field is set.
       */
      public boolean hasDuration() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * message Person中新增字段
       * </pre>
       *
       * <code>optional .google.protobuf.Duration duration = 6;</code>
       * @return The duration.
       */
      public com.google.protobuf.Duration getDuration() {
        if (durationBuilder_ == null) {
          return duration_ == null ? com.google.protobuf.Duration.getDefaultInstance() : duration_;
        } else {
          return durationBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * message Person中新增字段
       * </pre>
       *
       * <code>optional .google.protobuf.Duration duration = 6;</code>
       */
      public Builder setDuration(com.google.protobuf.Duration value) {
        if (durationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          duration_ = value;
          onChanged();
        } else {
          durationBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * message Person中新增字段
       * </pre>
       *
       * <code>optional .google.protobuf.Duration duration = 6;</code>
       */
      public Builder setDuration(
          com.google.protobuf.Duration.Builder builderForValue) {
        if (durationBuilder_ == null) {
          duration_ = builderForValue.build();
          onChanged();
        } else {
          durationBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * message Person中新增字段
       * </pre>
       *
       * <code>optional .google.protobuf.Duration duration = 6;</code>
       */
      public Builder mergeDuration(com.google.protobuf.Duration value) {
        if (durationBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              duration_ != null &&
              duration_ != com.google.protobuf.Duration.getDefaultInstance()) {
            duration_ =
              com.google.protobuf.Duration.newBuilder(duration_).mergeFrom(value).buildPartial();
          } else {
            duration_ = value;
          }
          onChanged();
        } else {
          durationBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * message Person中新增字段
       * </pre>
       *
       * <code>optional .google.protobuf.Duration duration = 6;</code>
       */
      public Builder clearDuration() {
        if (durationBuilder_ == null) {
          duration_ = null;
          onChanged();
        } else {
          durationBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <pre>
       * message Person中新增字段
       * </pre>
       *
       * <code>optional .google.protobuf.Duration duration = 6;</code>
       */
      public com.google.protobuf.Duration.Builder getDurationBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getDurationFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * message Person中新增字段
       * </pre>
       *
       * <code>optional .google.protobuf.Duration duration = 6;</code>
       */
      public com.google.protobuf.DurationOrBuilder getDurationOrBuilder() {
        if (durationBuilder_ != null) {
          return durationBuilder_.getMessageOrBuilder();
        } else {
          return duration_ == null ?
              com.google.protobuf.Duration.getDefaultInstance() : duration_;
        }
      }
      /**
       * <pre>
       * message Person中新增字段
       * </pre>
       *
       * <code>optional .google.protobuf.Duration duration = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder> 
          getDurationFieldBuilder() {
        if (durationBuilder_ == null) {
          durationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Duration, com.google.protobuf.Duration.Builder, com.google.protobuf.DurationOrBuilder>(
                  getDuration(),
                  getParentForChildren(),
                  isClean());
          duration_ = null;
        }
        return durationBuilder_;
      }

      private int number_ ;
      /**
       * <code>optional int32 number = 1;</code>
       * @return Whether the number field is set.
       */
      @java.lang.Override
      public boolean hasNumber() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 number = 1;</code>
       * @return The number.
       */
      @java.lang.Override
      public int getNumber() {
        return number_;
      }
      /**
       * <code>optional int32 number = 1;</code>
       * @param value The number to set.
       * @return This builder for chaining.
       */
      public Builder setNumber(int value) {
        bitField0_ |= 0x00000002;
        number_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 number = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        number_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }

      private int sex_ ;
      /**
       * <code>optional int32 sex = 3;</code>
       * @return Whether the sex field is set.
       */
      @java.lang.Override
      public boolean hasSex() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional int32 sex = 3;</code>
       * @return The sex.
       */
      @java.lang.Override
      public int getSex() {
        return sex_;
      }
      /**
       * <code>optional int32 sex = 3;</code>
       * @param value The sex to set.
       * @return This builder for chaining.
       */
      public Builder setSex(int value) {
        bitField0_ |= 0x00000008;
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 sex = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSex() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sex_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object hobby_ = "";
      /**
       * <code>optional string hobby = 4;</code>
       * @return Whether the hobby field is set.
       */
      public boolean hasHobby() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string hobby = 4;</code>
       * @return The hobby.
       */
      public java.lang.String getHobby() {
        java.lang.Object ref = hobby_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hobby_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string hobby = 4;</code>
       * @return The bytes for hobby.
       */
      public com.google.protobuf.ByteString
          getHobbyBytes() {
        java.lang.Object ref = hobby_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hobby_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string hobby = 4;</code>
       * @param value The hobby to set.
       * @return This builder for chaining.
       */
      public Builder setHobby(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        hobby_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string hobby = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearHobby() {
        bitField0_ = (bitField0_ & ~0x00000010);
        hobby_ = getDefaultInstance().getHobby();
        onChanged();
        return this;
      }
      /**
       * <code>optional string hobby = 4;</code>
       * @param value The bytes for hobby to set.
       * @return This builder for chaining.
       */
      public Builder setHobbyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000010;
        hobby_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object skill_ = "";
      /**
       * <code>optional string skill = 5;</code>
       * @return Whether the skill field is set.
       */
      public boolean hasSkill() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional string skill = 5;</code>
       * @return The skill.
       */
      public java.lang.String getSkill() {
        java.lang.Object ref = skill_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          skill_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string skill = 5;</code>
       * @return The bytes for skill.
       */
      public com.google.protobuf.ByteString
          getSkillBytes() {
        java.lang.Object ref = skill_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          skill_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string skill = 5;</code>
       * @param value The skill to set.
       * @return This builder for chaining.
       */
      public Builder setSkill(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        skill_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string skill = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSkill() {
        bitField0_ = (bitField0_ & ~0x00000020);
        skill_ = getDefaultInstance().getSkill();
        onChanged();
        return this;
      }
      /**
       * <code>optional string skill = 5;</code>
       * @param value The bytes for skill to set.
       * @return This builder for chaining.
       */
      public Builder setSkillBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000020;
        skill_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Student)
    }

    // @@protoc_insertion_point(class_scope:Student)
    private static final com.xzkj.ossService.entity.TStudent.Student DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xzkj.ossService.entity.TStudent.Student();
    }

    public static com.xzkj.ossService.entity.TStudent.Student getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Student>
        PARSER = new com.google.protobuf.AbstractParser<Student>() {
      @java.lang.Override
      public Student parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Student> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Student> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xzkj.ossService.entity.TStudent.Student getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Student_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Student_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rStudent.proto\032\036google/protobuf/duratio" +
      "n.proto\"\332\001\n\007Student\0220\n\010duration\030\006 \001(\0132\031." +
      "google.protobuf.DurationH\000\210\001\001\022\023\n\006number\030" +
      "\001 \001(\005H\001\210\001\001\022\021\n\004name\030\002 \001(\tH\002\210\001\001\022\020\n\003sex\030\003 \001" +
      "(\005H\003\210\001\001\022\022\n\005hobby\030\004 \001(\tH\004\210\001\001\022\022\n\005skill\030\005 \001" +
      "(\tH\005\210\001\001B\013\n\t_durationB\t\n\007_numberB\007\n\005_name" +
      "B\006\n\004_sexB\010\n\006_hobbyB\010\n\006_skillB&\n\032com.xzkj" +
      ".ossService.entityB\010TStudentb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DurationProto.getDescriptor(),
        });
    internal_static_Student_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Student_descriptor,
        new java.lang.String[] { "Duration", "Number", "Name", "Sex", "Hobby", "Skill", "Duration", "Number", "Name", "Sex", "Hobby", "Skill", });
    com.google.protobuf.DurationProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
