server:
  port: 9005
  tomcat:
    uri-encoding: utf-8
    max-threads: 1000
    min-spare-threads: 30
  servlet:
    context-path: /
spring:
  application:
    name: flow-oss
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      bucketname: edu-manager-lmh
      keyid: LTAI5tBqg3TcCfGb4gFpZEbg
      keysecret: QAl1n9iXEmeoWiuPQFkNMXo4YlAT6I


eureka:
  client:
    #表示是否将自己注册进Eurekaserver默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:9001/eureka